# Generated by Django 5.2.5 on 2025-08-30 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(max_length=42)),
                ('usdt_amount', models.DecimalField(decimal_places=6, max_digits=20)),
                ('fecoin_amount', models.DecimalField(decimal_places=6, max_digits=20)),
                ('transaction_hash', models.CharField(max_length=66, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
